# -*- coding: utf-8 -*-
"""contVocalRecursivo.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13YGksQVtTOtUd9dcbwwV1PEEJUIUTh9S
"""

class ContadorVocales:
    def __init__(self, cadena):
        """
        Inicializa la clase con una cadena de texto.

        :param cadena: Texto donde se contarán las vocales
        """
        self.cadena = cadena

    def contar(self):
        """
        Método público que inicia el conteo de vocales en la cadena.

        :return: Número total de vocales
        """
        return self._contar_vocales_recursivo(self.cadena)

    def _contar_vocales_recursivo(self, texto):
        """
        Método recursivo privado para contar vocales en el texto.

        :param texto: Cadena actual en la recursión
        :return: Número de vocales encontradas
        """
        if texto == "":
            return 0
        elif texto[0].lower() in 'aeiou':
            return 1 + self._contar_vocales_recursivo(texto[1:])
        else:
            return self._contar_vocales_recursivo(texto[1:])


# Ejemplo de uso:
contador = ContadorVocales("Recursividad")
print(contador.contar())  # Salida: 5